[tool.poetry]
name = "meteofrance-api"
version = "0.1.0"
license = "MIT"
description = "Python client for Météo-France API."
authors = ["oncleben31 <oncleben31@gmail.com>"]
homepage = "https://github.com/hacf-fr/meteofrance-api"
repository = "https://github.com/hacf-fr/meteofrance-api"
keywords = ["weather", "weather-api", "meteo"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.24.0"
pytz = "^2020.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
